eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: userboot
